Courses status
ArianePhelizot/asanasano pull request #52
Opened 2017-05-25 12:54 UTC by ArianePhelizot

Hello @Guillaumejfrt ,

Eventually la pull request sur le changement du statut du cours.
Avant de plonger en direct live dans sa relecture, je t'invite à jeter un petit coup d'oeil à la carte correspondante du trello où j'ai détaillé pas à pas ce que je faisais. Tu trouveras ici le lien direct vers la dite carte: https://trello.com/c/8nSaPnjc.

Il y aura pas mal de petits trucs à optimiser côté front. Mais a priori ce que j'ai fait n'a déjà pas tout pêté.

J'ai galéré à définir les bonnes routes...d'où de multiples allers/retours dans les commits sur le sujet. Next time, je me baserais complètement sur Gitx que je commence à savoir utilisé, cela fera moins de commits et des commits plus pertinents.

Tu trouveras l'intégration de la config de test dans cette pull request. C'est normal si je puis dire. Je l'ai fait avec Colin...puis on a abandonné car il y avait trop de dépendance entre nos modèles et cela s'est avéré beaucoup plus compliqué que prévu. Pour autant si on en a besoin à un autre moment, elle sera là. Les fixtures en revanche n'ont pas été commitées.

A ta dispo surtout en cas de besoin.

Cheers!

Ariane

2017-05-26 10:45 UTC, Guillaumejfrt requested changes

2017-05-26 10:45 UTC, Guillaumejfrt commented on config/routes.rb
>      patch "courses/:id/publish", to: "courses#publish", as: :course_publish
Je pense que tu n'as pas besoin de nester tes deux routes `courses/:id/publish` et `courses/:id/depublish` sous group && course car à aucun moment tu utilises l'id du group dans les actions `publish` et `depublish` dans le contrôleur `groups`. 

Par conséquent, je pense que tu peux simplifier tes routes de la façon suivante (à écrire juste après `root to: 'pages#home'` par exemple):

`resources :courses do`
     `member do`
        `get "publish", to: "courses#publish", as: :course_publish`
        `get "depublish", to: "courses#depublish", as: :course_depublish`
     `end`
`end`

=> cela va générer les routes suivantes `courses/:id/publish` et `courses/:id/depublish`

=> impact direct dans ton contrôleur de groups: 

      1. tu peux sortir `:publish` du `before_action :find_group`
      2. tu peux ajouter `:depublish` dans le `before_action :find_course`

=> impact direct dans ta vue de course: 

les liens `group_course_publish_path(@group, @course)` et `group_course_depublish_path(@group, @course)` deviennent respectivement: `course_publish_path(@course)` et `course_depublish_path(@group, @course)`.

2017-05-26 10:54 UTC, Guillaumejfrt requested changes

2017-05-26 10:54 UTC, Guillaumejfrt commented on app/controllers/courses_controller.rb
> +  before_action :find_group, only: [:new, :create, :edit, :update, :publish]
Tu n'utilises pas le group_id dans tes deux actions #publish et #despublish. On n'a donc pas besoin d'insérer `:publish` dans le `before_action :find_group`

2017-05-26 10:54 UTC, Guillaumejfrt commented on app/controllers/courses_controller.rb
> +  before_action :find_course, only: [:show, :edit, :update, :destroy, :publish]
il faut ajouter `:depublish` dans le `before_action :find_course` pour avoir le course_id et le `authorize @course`

2017-05-26 10:55 UTC, Guillaumejfrt requested changes

2017-05-26 10:55 UTC, Guillaumejfrt commented on app/views/courses/show.html.erb
> +                  <%= link_to "Désactiver le cours", group_course_depublish_path(@group, @course),
modifier le helper `group_course_depublish_path(@group, @course)` en `course_depublish_path(@course)`

2017-05-26 10:55 UTC, Guillaumejfrt commented on app/views/courses/show.html.erb
> +                <%= link_to "Publier le cours", group_course_publish_path(@group, @course),
modifier le helper `group_course_publish_path(@group, @course)` en `course_publish_path(@course)`

2017-05-27 08:05 UTC, ArianePhelizot commented on app/controllers/courses_controller.rb
> +  before_action :find_group, only: [:new, :create, :edit, :update, :publish]
done

2017-05-27 08:05 UTC, ArianePhelizot commented on app/controllers/courses_controller.rb
> +  before_action :find_course, only: [:show, :edit, :update, :destroy, :publish]
done

2017-05-27 08:16 UTC, ArianePhelizot commented on config/routes.rb
>      patch "courses/:id/publish", to: "courses#publish", as: :course_publish
Bien vu sur la logique
Pour moi le "   resources :courses do
member do", n'était pas nécessaire en préalable. J'ai tenté sans et cela fonctionne.

Mes routes sont en patch (et non en get) car il s'agit d'update.

Impact géré dans les vues tout semble fonctionner

2017-05-28 08:38 UTC, merged